[package]
name = "wair"
version = "0.1.0"
authors = ["Benjamin Saunders <ben.e.saunders@gmail.com>"]

[features]
x11 = ["x11-dl", "libc"]
wayland = ["wayland-client"]

[dependencies]
log = "0.3.6"
mio = "0.6.0"
tokio-core = "0.1"
x11-dl = { version = "2.8.0", optional = true }
futures = "0.1.1"
libc = { version = "0.2.0", optional = true }
wayland-client = { version = "0.6.2", optional = true }
env_logger = "0.3.5"
